spring:
  profiles:
    include: default
datasource:
  hikari:
    jdbc-url: "jdbc:postgresql://localhost:5432/booking_hotel"
    maximum-pool-size: 20
  username: postgres
  password: postgres
  url: "jdbc:postgresql://localhost:5432/booking_hotel"
jwtconfig:
  secret: secret
  expiration: 6000000